#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace specp.Domain.Repository
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Darwin-Dev")]
	public partial class SVCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SVCDataContext() : 
				base(global::specp.Domain.Properties.Settings.Default.Darwin_DevConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SVCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SVCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SVCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SVCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SvcIns_AppServiceRun")]
		public ISingleResult<SvcIns_AppServiceRunResult> SvcIns_AppServiceRun([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_AppServiceID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_StartedAt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_StatusID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_CreatedByID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] ref string tState)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_AppServiceID, p_StartedAt, p_StatusID, p_CreatedByID, tState);
			tState = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SvcIns_AppServiceRunResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SvcUpd_AppServiceRun")]
		public int SvcUpd_AppServiceRun([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_AppServiceRunID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_FinishedAt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_StatusID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_LastModifiedByID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] ref string tState)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_AppServiceRunID, p_FinishedAt, p_StatusID, p_LastModifiedByID, tState);
			tState = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SvcIns_AppServiceRunResult
	{
		
		private int _AppServiceRunID;
		
		private System.Nullable<int> _AppServiceID;
		
		private System.DateTime _StartedAt;
		
		private System.DateTime _FinishedAt;
		
		private int _StatusID;
		
		private int _CreatedByID;
		
		private System.DateTime _CreatedAt;
		
		private int _LastModifiedByID;
		
		private System.DateTime _LastModifiedAt;
		
		public SvcIns_AppServiceRunResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppServiceRunID", DbType="Int NOT NULL")]
		public int AppServiceRunID
		{
			get
			{
				return this._AppServiceRunID;
			}
			set
			{
				if ((this._AppServiceRunID != value))
				{
					this._AppServiceRunID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppServiceID", DbType="Int")]
		public System.Nullable<int> AppServiceID
		{
			get
			{
				return this._AppServiceID;
			}
			set
			{
				if ((this._AppServiceID != value))
				{
					this._AppServiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartedAt", DbType="DateTime NOT NULL")]
		public System.DateTime StartedAt
		{
			get
			{
				return this._StartedAt;
			}
			set
			{
				if ((this._StartedAt != value))
				{
					this._StartedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedAt", DbType="DateTime NOT NULL")]
		public System.DateTime FinishedAt
		{
			get
			{
				return this._FinishedAt;
			}
			set
			{
				if ((this._FinishedAt != value))
				{
					this._FinishedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int NOT NULL")]
		public int StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByID", DbType="Int NOT NULL")]
		public int CreatedByID
		{
			get
			{
				return this._CreatedByID;
			}
			set
			{
				if ((this._CreatedByID != value))
				{
					this._CreatedByID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this._CreatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByID", DbType="Int NOT NULL")]
		public int LastModifiedByID
		{
			get
			{
				return this._LastModifiedByID;
			}
			set
			{
				if ((this._LastModifiedByID != value))
				{
					this._LastModifiedByID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedAt", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedAt
		{
			get
			{
				return this._LastModifiedAt;
			}
			set
			{
				if ((this._LastModifiedAt != value))
				{
					this._LastModifiedAt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
