<?xml version="1.0" encoding="utf-8"?><Database Name="Darwin-Dev" Class="SVCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tserver;Initial Catalog=Darwin-Dev;User ID=sa" SettingsObjectName="specp.Domain.Properties.Settings" SettingsPropertyName="Darwin_DevConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SvcIns_AppServiceRun" Method="SvcIns_AppServiceRun">
    <Parameter Name="p_AppServiceID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_StartedAt" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_StatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_CreatedByID" Type="System.Int32" DbType="Int" />
    <Parameter Name="tState" Type="System.String" DbType="VarChar(500)" Direction="InOut" />
    <ElementType Name="SvcIns_AppServiceRunResult">
      <Column Name="AppServiceRunID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppServiceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FinishedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SvcUpd_AppServiceRun" Method="SvcUpd_AppServiceRun">
    <Parameter Name="p_AppServiceRunID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_FinishedAt" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_StatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_LastModifiedByID" Type="System.Int32" DbType="Int" />
    <Parameter Name="tState" Type="System.String" DbType="VarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SvcIns_AppServiceRunQueue" Method="SvcIns_AppServiceRunQueue">
    <Parameter Name="p_AppServiceRunID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_AppServiceQueueID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_StateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_Retry" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_StatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_CreatedByID" Type="System.Int32" DbType="Int" />
    <Parameter Name="tState" Type="System.String" DbType="VarChar(500)" Direction="InOut" />
    <ElementType Name="SvcIns_AppServiceRunQueueResult">
      <Column Name="AppServiceRunQueueID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppServiceRunID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AppServiceQueueID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Retry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SvcUpd_AppServiceQueue" Method="SvcUpd_AppServiceQueue">
    <Parameter Name="p_AppServiceQueueID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_FileName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="p_RetryAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_StateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_StatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_LastModifiedByID" Type="System.Int32" DbType="Int" />
    <Parameter Name="tState" Type="System.String" DbType="VarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SvcGet_AppServiceQueue" Method="SvcGet_AppServiceQueue">
    <Parameter Name="p_StateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_AppServiceQueueID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_FileName" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="tState" Type="System.String" DbType="VarChar(500)" Direction="InOut" />
    <ElementType Name="SvcGet_AppServiceQueueResult">
      <Column Name="AppServiceQueueID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppServiceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MapObjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MapObjectTargetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RetryAttempts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedByID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SvcIns_AppServiceRunLog" Method="SvcIns_AppServiceRunLog">
    <Parameter Name="p_AppServiceID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_AppServiceRunID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_AppServiceQueueID" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_LogLevel" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_LogMessage" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="p_LogTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_CreatedByID" Type="System.Int32" DbType="Int" />
    <Parameter Name="tState" Type="System.String" DbType="VarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>